//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyawoPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbMyPortfolioEntities : DbContext
    {
        public DbMyPortfolioEntities()
            : base("name=DbMyPortfolioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAbout> tblAbout { get; set; }
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblContact> tblContact { get; set; }
        public virtual DbSet<tblFuture> tblFuture { get; set; }
        public virtual DbSet<tblProject> tblProject { get; set; }
        public virtual DbSet<tblService> tblService { get; set; }
        public virtual DbSet<tblSocialMedia> tblSocialMedia { get; set; }
        public virtual DbSet<tblTestimonial> tblTestimonial { get; set; }
        public virtual DbSet<tblPricing> tblPricing { get; set; }
    
        public virtual ObjectResult<string> LastProjectName()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("LastProjectName");
        }
    
        public virtual ObjectResult<string> FirstPricing()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("FirstPricing");
        }
    }
}
